### ISSUE TITLE
Conflict with mod [T] MoreBedsCloth

### ISSUE THREAD

**Issue by Taranchuk** [DrZhivago1/DocWorld#18]
With a mod[T] MoreBedsCloth the game requires two sets of cloth for beds. For a single bed, it requires 12 and 12 clothes, for a double bed it requires 18 and 18 clothes.

**Comment by DrZhivago1** [comment]
Ah yes, that'd be due to the fact that this mod does exactly what that mod would do. This issue is a reminder to me to include better integration with WSB though. I'll try to get around to it, shame I just posted updates and everything haha.

**Comment by DrZhivago1** [comment]
Either:
A-Stop using that mod
B-Remove the ClothBeds patch from the patches folder.
