### ISSUE TITLE
Support for mod Vanilla Furniture Expanded - Spacer Module

### ISSUE THREAD

**Issue by Taranchuk** [DrZhivago1/DocWorld#19]
New mod released: https://steamcommunity.com/sharedfiles/filedetails/?id=1836382920
Because your mod removes the designation category in the mod and may somehow interfere with Vanilla Furniture Expanded mods, the debug log is full of red errors. Can you make mods compatible with each other? Here is the Hugslib log:
https://gist.github.com/baa286a4651a8e6c3a4fac45a561aa62

**Comment by DrZhivago1** [comment]
Definitely get that patched in the next update. Thanks for the info.

**Comment by DrZhivago1** [comment]
Temporary fix:
Delete "VFE_DesignationCategory.xml" from patches folder.
