### ISSUE TITLE
I made some patches for CTS, Sparkling Worlds, Glass + Lights, VFE, VFE - SM, Glitter Tech, RJW

### ISSUE THREAD

**Issue by Taranchuk** [DrZhivago1/DocWorld#23]
I found that some beds do not require clothes for building and some things are not in more suitable categories. So I made patches that do this:

~~Glitter Tech - moves Re-Ambulation Pod to a bed category, moves Flood light to the Lightning category
Glass+Lights - Moves outdoor groundlamp to Lightning category
Sparkling Worlds - moves GlitterworldHospitalBedSW to the Lightning category
CTS - Complete Tech Solutions - moves Hi-tech Hospital Beds to the Beds category
RJW - moves all beds to the Beds category and gives them the requirement of clothes for building
VFE and VFE SM - gives all beds the requirement of clothes for building~~

Feel free to add these patches to DocWorld mod, since I do not know how to add pull requests, I attach them with the archive.
[Patches.zip](https://github.com/DrZhivago1/DocWorld/files/3516532/Patches.zip)

**Comment by DrZhivago1** [comment]
Thanks, I'll look into it. The Glass+Lights is now fixed on Master.

**Comment by DrZhivago1** [comment]
Thanks, all integrated.
