### ISSUE TITLE
Problem with the mod RimCuisine 2 Bottling and Brewing Expansion

### ISSUE THREAD

**Issue by Taranchuk** [DrZhivago1/DocWorld#27]
On the new version, it seems there is incompatibility with the RimCuisine 2 Bottling and Brewing Expansion mod. Errors report the inability to give DesignationCategory RC2_RimCuisine to things. After I delete the Bottling and Brewing mod there are no red red errors. Here is the log: https://gist.github.com/HugsLibRecordKeeper/35797598b3316f9e0a8c5dda31aa0f0d

**Comment by DrZhivago1** [comment]
That's with using the latest released version and not from master?

**Comment by Taranchuk** [comment]
Yes, with the latest released version, not from master.

**Comment by DrZhivago1** [comment]
Did you remove a patch?

**Comment by Taranchuk** [comment]
Which patch? I did not change anything in the mod.

**Comment by DrZhivago1** [comment]
Because I can't reproduce the error.

https://gist.github.com/HugsLibRecordKeeper/5d2c274362b96519152922f09069d8d8

**Comment by DrZhivago1** [comment]
Try this:
Delete/reinstall all RimCuisine 2 mods, as well as DocWorld

**Comment by Taranchuk** [comment]
Maybe the mods got updates, I'll try to get them, I'm not on Steam, sorry for the inconvenience!

**Comment by DrZhivago1** [comment]
Basically in your log the "booze expansion" is looking for a category I removed and replaced... But it shouldn't be searching for the category, because I replaced it. So idk. Can't reproduce the error, but let me know if you're still having problems after clean re-installs.

**Comment by Taranchuk** [comment]
This seems to be a problem with the name of the mod. I have it recorded as [1.0] RimCuisine 2: Bottling and Brewing Expansion, and you have it as [1.0] RimCuisine 2: Bottling and Booze Expansion:. Maybe the author just updated the name of the mod.

**Comment by DrZhivago1** [comment]
I took the name of the mod from Steam, so maybe there is a difference there. Weird. Good catch though.

**Comment by Taranchuk** [comment]
The author actually changed the name to Booze expansion. I replaced the name in About.xml and now everything is ok.

**Comment by DrZhivago1** [comment]
Well, good to hear. Enjoy the update! Let me know if you find anything else funky.
