### ISSUE TITLE
Chandeliers from Additional Joy Objects do not move to the Lightning category

### ISSUE THREAD

**Issue by Taranchuk** [DrZhivago1/DocWorld#38]
Perhaps the mod was updated or the case is in a different version, I use this project: https://github.com/dninemfive/ajo-lite
also patch adding glass to the chandeliers does not work

**Comment by DrZhivago1** [comment]
I cannot reproduce the error.

Are you using the latest released version of my mod? Or is it from Master?
Have you tried loading only DocWorld and AJO-Lite?
Do you have a HugsLib Error log?

**Comment by DrZhivago1** [comment]
Also ensure that you have the latest version of AJO-Lite. There was a mod name change a couple months ago.

**Comment by Taranchuk** [comment]
Yes, that was the case. About.xml was old, since I did not care to replace it. Sorry for the trouble.
