### ISSUE TITLE
1.1 Dropdown Suggestions 

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#47]
### I don't quite remember what was already patched in 1.0 and what you've already done for 1.1, but here are some dropdown suggestions, mainly for VFE Power & Production, but not only. All the mentionned mods should be on the workshop:
_________________________________________________________________
- Power generators (Wood and Chemfuel - Vanilla) should be in a drop-down menu with:
- [x] Helixen, industrial and portable generators [Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)
- [x] Kerosene generator ([Jetpack](https://steamcommunity.com/sharedfiles/filedetails/?id=2002341555));
- [x] Cryo-stabilised generator ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502));
- [x] Hempoline powered generator ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936));
_________________________________________________________________
- Solar generator (Vanilla) should be in a drop-down menu with:
- [x] Advanced version ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
- [x] Hempene Solar Generator ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936));
- [x] Alcyonite Solar generator ([Alpha Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677));
- [x] Small solar graphene generator & Graphene solar generator ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________
- Geothermal generator (Vanilla) should be in a drop-down menu with:
- [x] Graphene geothermal generator ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________
- Wind turbine (Vanilla) should be in a drop-down menu with:
- [x] Graphene wind turbine ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
- [x] Advanced version ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
- [x] Windmill ([Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119));
_________________________________________________________________
- Watermill generator (Vanilla) should be in a drop-down menu with:
- [x] Advanced version ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
_________________________________________________________________

- Batteries (Vanilla) should be in a drop-down menu with:
- [x] The batteries added by SYR ([SYR (Metallic Batteries)](https://steamcommunity.com/sharedfiles/filedetails/?id=1489425285));
- [x] The small, large and advanced batteries ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
- [x] Small graphene battery & Graphene battery ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________
- Power conduits (Vanilla) should be in a drop-down menu with:
- ~~Graphene Conduit & Underground Graphene conduit ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));~~
**Due to harmony patching, the underground conduits cannot be properly added into a dropdown menu. Therefore DocWorld will not touch the conduits.**
- [x] Hempene Power Conduit ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936));
_________________________________________________________________

- Heater (Vanilla) should be in a drop-down menus with:
- [x] Propane heater ([Alpha Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677));
- [x] Gas heater ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
- [x] Graphene Heater ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
- [x] Chemboiler ([Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119));
_________________________________________________________________

- Cooler (Vanilla) should be in a drop-down menu with:
- [x] Gas cooler ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
- [x] Graphene Cooler ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________

- Gas pipe ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)) should be in a drop-down menu with:
- [x] Subterranean gas pipe ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
_________________________________________________________________
- All the floors from ([Rimoleum](https://steamcommunity.com/sharedfiles/filedetails/?id=2004334162)) should be in the same drop-down menu;
**Moved to Floors, decided no drop-down menu will be applied**
_________________________________________________________________
- RimPlas Injection Moulder ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331)) should be in the same drop-down menu with:
- [x] Advanced RimPlas injection Moulder ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________
- Fueled Glassworks ([Glass+Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=826153738)) should be in a drop-down menus with:
- [x] Electric Glassworks ([Glass+Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=826153738));
- [x] Reinforced Glassworks ([Glass+Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=826153738));
_________________________________________________________________

- Transport pod (Vanilla) should be in a drop-down menu with:
- [x] Beam cannon satellite pod & Bombardment sattelite pod ([Sparkling Worlds - Full mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922));
_________________________________________________________________
- Tool cabinet (Vanilla) should be in a drop-down menu with:
- [x] All the new cabinets ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632));
_________________________________________________________________
- Fabrication bench (Vanilla) should be in a drop-down menu with:
- ~~Assembly Bench ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632));~~
**Won't be done**
_________________________________________________________________
- Bridge (Vanilla) should be in a drop-down menus with:
- ~~Concrete bridge ([Roads of the Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1613783924));~~
**Won't be done**
_________________________________________________________________
- Stove (fueled & electric - Vanilla) should be in a drop-down menu with:
- [x] Large stove ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632));
- [x] Propane stove ([Alpha Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677));
- [x] Charcoal stove ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851));
_________________________________________________________________
- Smelter (Vanilla) should be in a drop-down menu with:
- [x] Fueled smelter ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632));
- [x] Both exotic smelters ([Alpha Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677));
- [x] Helixien gas smelter ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477));
_________________________________________________________________
- Smithy, machining table (fueled and electric) should respectively be in a drop-down menu with:
- [x] Large versions ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632));
- [x] Charcoal Smithy ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851));
_________________________________________________________________
- Huge bear rug ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502)) should be in a drop-down menu with:
- [x] Huge bearcat rug ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502));
- [x] Wolf rug ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502));
- [x] Muffalo pelt rug ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502));
_________________________________________________________________
- Vitals monitor (Vanilla) should be in a drop-down menu with:
- [x] Walls vitals monitor ([Walls vitals monitor](https://steamcommunity.com/sharedfiles/filedetails/?id=1334289344));
_________________________________________________________________
- Autocannon turret (Vanilla) should be in a drop-down menu with:
- [x] Double Autocannon ([Vanilla Furniture Expanded - Security](https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007
));
- [x] Maybe also the Uranium slug turret (Vanilla);
_________________________________________________________________
- The IED trap (Vanilla) should be in a drop-down menu with:
- [x] IED nitromilk trap ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502));
_________________________________________________________________
- Shield generator (portable) ([[O21] Shield Generators](https://steamcommunity.com/sharedfiles/filedetails/?id=2069177490
)) should be in a drop-down menu with:
- Shield generator (medium) ([[O21] Shield Generators](https://steamcommunity.com/sharedfiles/filedetails/?id=2069177490
));
- Shield generator (Large) ([[O21] Shield Generators](https://steamcommunity.com/sharedfiles/filedetails/?id=2069177490
));
**Cannot be done, mod removed**
_________________________________________________________________
- Tube television (Vanilla) should be in a drop-down menu with:
- [x] Ultrascreen television ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079
 ));
- [x] Flatscreen television (Vanilla);
- [x] Glassworks TV ([Glass+Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=826153738)); 
- [x] Wallmounted Flatscreen TV ([[ELIF] Flooring and Decorative Options](https://steamcommunity.com/sharedfiles/filedetails/?id=2075187420));
_________________________________________________________________
- Orbital Trade Beacon (Vanilla) should be in a drop-down menu with:
- [x] Orbital Trade Column ([Utility Columns](https://steamcommunity.com/sharedfiles/filedetails/?id=2013476665));
_________________________________________________________________
- Organ Vat ([Questionable Ethics Enhanced](https://steamcommunity.com/sharedfiles/filedetails/?id=1787359789)) should be in the same drop-down menu with:
- [x] Clone Vat ([Questionable Ethics Enhanced](https://steamcommunity.com/sharedfiles/filedetails/?id=1787359789));
_________________________________________________________________
- Standing Lamp (Vanilla) should be in a drop-down menu with:
- [x] The  magenta, lime, aqua, yellow, purple and orange standing lamps ([More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850));
_________________________________________________________________
- ~~The Modern Lamp ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143)) should be in a drop-down menu with:~~
- ~~The Spacer Lamp ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=1836382920));~~
**Will not be done**
_________________________________________________________________
- ~~The Ceiling Lamps ([Glass+Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=826153738)) should be in a drop-down menu with:~~
**Separate but in their own Dropdown**
- [x] Ceiling light ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
- [x] Graphene ceiling light ([RimPlas](https://steamcommunity.com/workshop/filedetails/?id=2004190331));
_________________________________________________________________

**Comment by DrZhivago1** [comment]
I'm not quite understanding this. If you could format it like this:
`
Provide a link to the mod/s you wish to see patched, and a description of what you want to see. Please be concise in your description, as I likely do not use all the mods you people do, and I need to get your ideas into my brain box. Otherwise I'll largely ignore the request.

EG:

Both Mod1 and Mod2 use grapes. They are used in fermenting and growing. I would like them to be merged.
[relevant mod links]

Alien1 from Mod1 eats grapes from Mod2 and they shouldn't.
[relevant mod links]`

**Comment by LeriWeill** [comment]
When I wrote my post it looked understandable to me, seems it wasn't the case 😄  
I clarified everything and added links, hope it helps!

**Comment by DrZhivago1** [comment]
Ah wonderful, this makes much more sense to me haha. Thanks. I'll look into it once I've finalized catching up with the 1.0->1.1 patches. 949 more to go 😅

**Comment by LeriWeill** [comment]
Yep, I've been switching between Rimworld and GitHub to edit the post with the relevant suggestions, I'm done for tonight at least :D

**Comment by DrZhivago1** [comment]
There are issues when trying to add _Underground Graphene Conduits_ to a dropdown menu. The author and I have talked about it, but no fix atm.

**Comment by LeriWeill** [comment]
Yeah I saw you asking questions on Pelador's Discord! No worries, take your time :D
