### ISSUE TITLE
1.1 Testing - Rimkea log

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#48]
A few days ago I told you about an error happening with Rimkea and DocWorld. After many testings, adding and removing mods, I didn't manage to find the culprit, so here's the output log with all my mods loaded : https://gist.github.com/HugsLibRecordKeeper/a510ccf59206302469673ca93f4e7b26
First interesting thing is at line 1914 : 

`XML error: Could not find parent node named "RIKFleaLampBase" for node "ThingDef". Full node: <ThingDef ParentName="RIKFleaLampBase"><defName>KAGESHAINLamp</defName><label>KAGESHAIN Lamp</label><description>KAGESHAIN Lamp
There have not been many KAGESHAIN lamps produced.
It had a small design flaw where the cage prevented
the bulb to be replaced. People actually cared about that.</description><graphicData><texPath>Things/Buildings/Furniture/Lamps/KAGESHAINLamp</texPath></graphicData><comps><li Class="CompProperties_Glower"><glowRadius>15</glowRadius><glowColor>(217,217,217,0)</glowColor></li></comps></ThingDef>
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)`

There's a few others like that, and other Rimkea related errors at line 2303:
`ThingDef KAGESHAINLamp has no thingClass. This is a misconfiguration in RIMkea.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)`

Then there's a minor error line 1983:

`[DocWorld] Patch operation Verse.PatchOperationFindMod(Smokeleaf Industry Reborn) failed
file: [Rimworld_dir]\Mods\DocWorld-1.1_Testing\Patches\Remove_Designation_Category.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)`

Finally, the Fence tab is not appearing in my game, and there are errors like the one at line 1987:

`Could not resolve cross-reference: No Verse.DesignationCategoryDef named DZ_Fences found to give to Verse.ThingDef WoodFenceGateB
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)`

I hope all of these errors are DocWorld related and I'm not wasting your time. If it's the case, feel free to close this issue !

**Comment by DrZhivago1** [comment]
Ok thanks for reporting. Probably going to need to update/review the RIMkea lamp stuff.

The `thingClass` error would be an issue with the RIMkea mod itself.

The feces are not appearing because I haven't updated those patches yet.

I'm working on it a bit today so hopefully I can finish up the patches and start cleaning/adding new ones.

**Comment by LeriWeill** [comment]
Well, I thought it would be on my end, I'll have to test some more. The Smokeleaf Industry and Fences errors have dissapeared though, so that's that at least. I'll close this issue, thanks for the update!

**Comment by LeriWeill** [comment]
Reopened issue : here's a new log (https://gist.github.com/06fa2e69b108586979bfe3d951002041)
Found the culprit : when you load Harmony, Core, Royalty, HugsLib, **Glass+Lights**, Rimkea and DocWorld and I got the errors. Loaded G+L after Rimkea, same errors. Loaded without DocWorld, no error!

**Comment by DrZhivago1** [comment]
Made a typo, fixed it. RIMkea and Glass will function normally again.
