### ISSUE TITLE
1.1 Misc Suggestions

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#51]
It's me again with another issue! (I swear I'll leave you alone after this one... At least for a moment)
With the upcoming Props and Decoration module from Oskar that is soon to come, and seeing that Zen Garden creates a Decoration tab, I thought it could be used to de-clutter the Furniture Tab, so I made a few suggestions that go this way.

Put in Animal Tab: 
- [x] Invisible animal sleeping spot and Invisible animal bed ([[FSF] Invisible animal sleeping spot](https://steamcommunity.com/sharedfiles/filedetails/?id=1966744871)) _[From Furniture Tab]_
- [x] Animal Medical Bed ([Animal Medical Bed](https://steamcommunity.com/sharedfiles/filedetails/?id=2016958187)) _[From Furniture Tab]_
- [x] RimPlas Animal Box ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331)) _[From Beds Tab]_
_________________________________________________________________
Put in Fences Tab:
- [x] Small Fence and Concrete Fence ([(O21) Clutter Structures](https://steamcommunity.com/sharedfiles/filedetails/?id=2008681009))
_________________________________________________________________
Put in Floors Tab:
- [x] Gravels and paths ([Zen Garden](https://steamcommunity.com/sharedfiles/filedetails/?id=1554147049)) _[From Decoration Tab]_
**Only "Rough" and "Unraked" are actually floors, others kept in decoration**
- [x] Everything from [Rimoleum](https://steamcommunity.com/sharedfiles/filedetails/?id=2004334162) _[From Rimoleum Tab]_
_________________________________________________________________
Put in Decoration Tab (or in the Prop Tab, whatever):
- [x] Rimkea Rugs ([Rimkea](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959)) _[From Furniture Tab]_
- [x] Vanilla and modded plant pots ([Rimkea ](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959)and [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850)) _[From Furniture Tab]_
- [x] Animal Rugs and tusk ([Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502)) _[From Furniture Tab]_
- [x] All the stuff from [[ELIF] Flooring and Decorative Options](https://steamcommunity.com/sharedfiles/filedetails/?id=2075187420) _[From Decorations Tab]_ (Not the same as the Decoration Tab, FDO also has it's own category)
- [x] Everything from [Neon Rim : The Rimworld Signs Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2010569007) _[From Furniture Tab]_
- [x] Flower arc ([Zen Garden](https://steamcommunity.com/sharedfiles/filedetails/?id=1554147049)) _[From Misc Tab]_
- [x] Large Stele and Grand Stele _[From Misc Tab]_
- [x] Door mat (Orange) & Door mat (Red) ([Door Mat](https://steamcommunity.com/sharedfiles/filedetails/?id=1505423207)) _[From Misc Tab]_
- [x] Everything from [Vanilla Furniture Expanded - Props and Decor](https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149) _[From Props Tab]_
_________________________________________________________________
Put in Lighting Tab:
- [x] Half-wall and pedestral lantern ([Zen Garden](https://steamcommunity.com/sharedfiles/filedetails/?id=1554147049)) _[From Decoration Tab]_
- [x] Chemlamp post ([Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119)) _[From Furniture Tab]_
- [x] Candle ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851))
_________________________________________________________________
Put in Husbandry Tab:
- [x] Irrigation sprinkler & Biosolid Composters ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) _[From Hygiene Tab]_
- [x] Gas Sun Lamp ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)) _[From Lighting Tab]_
- [x] Potting Mix Composting barrel, Herb box, herb box (Limed), Potash barrel, preserving barrel, Water grower ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851))
_________________________________________________________________
Put in Culinary Tab:
- [x] Over-Wall Nutrient Paste Dispenser ([Over-Wall Nutrient Paste Dispenser](https://steamcommunity.com/sharedfiles/filedetails/?id=2074245348)) _[From Production Tab]_
- [x] Chemshine barrel ([Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119)) _[From Production Tab]_
- [x] Helixien Gas Stove ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)) _[From Production Tab]_
_________________________________________________________________
Put in Security Tab:
- [x] Spark grid, Napalm Trail & Napalm Bomb ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735)) _[From Industrial Tab]_
_________________________________________________________________
Put in Misc Tab:
- [x] Fire Sprinkler ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) _[From Hygiene Tab]_ (might be better in the Security tab, maybe)
_________________________________________________________________
Put in Temperature Tab: 
- [x] Air-Con Pipe, Radiator, Large radiator, Solar Heater, Ceiling Fan, Air-Con Indoor & outdoor Unit, Walk-in freezer unit ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) _[From Hygiene Tab]_
_________________________________________________________________
Drop-down menus:
- [x] Reactor Type A ([Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465)) should be in a drop-down menu with Reactor Type X ([Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465)) and Reactor type V ([Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465))
- [x] Thor Turbine ([Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465)) should be in a drop-down menu with Zeus Turbine ([Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465))
- [x] Chemfuel Power Plant ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735)) should be in a drop-down menu with Large chemfuel power plant ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735))
- [x] Oil Well ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735)) should be in a drop-down menu with Deep Oil Well ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735))
- [x] Wine Barrel ([Vanilla Factions Expanded - Medieval](https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450)) should be in a drop-down menu with - Fermenting Barrel (Vanilla) and Chemshine barrel ([Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119))
- [x] ~~Sterile Tiles (Vanilla) should be in a drop-down menu with Sterile Tiles ([Rimefeller](https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735))~~
**Potentially in the future with more sterile tile floors**
- [x] ~~Animal Sleeping Spot (Vanilla) should be in a drop-down menu with Invisible animal sleeping spot ([[FSF] Invisible animal sleeping spot](https://steamcommunity.com/sharedfiles/filedetails/?id=1966744871))~~
**Will maintain separation**
- [x] ~~Asphalt ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331)) should be in a drop-down menu with Concrete Tile and Paved Tile (Vanilla)~~
**Still view the floors as separate enough**
- [x] ~~Air-Con Indoor ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) should be in a drop-down menu with the outdoor Unit ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) and the Walk-in freezer unit ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268))~~
**Will confuse users, as they are distinct items**
- [x] ~~Passive Cooler (Vanilla) should be in a drop-down menu with Passive cooler (Ammonia)   ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851))~~
**There are many mods that make Passive Cooler "stuffable" so I will not add it to dropdown to reduce conflicts**
- [x] Water well ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) should be in a drop-down menu with Deep Water well ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268))
- [x] Electric Pump ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) should be in a drop-down menu with Pumping Station ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268))
- [x] Wood-fired generator (Vanilla) should be in a drop-down menu with Charcoal-fired generator ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851))
- [x] ~~Machining Table (Vanilla) should be in a dropdown menu with Mech Breaker ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331))~~
**Distinct enough table**
_________________________________________________________________
Linkables:
- [ ] Glitterworld Hospital Bed ([Sparkling Worlds - Full Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922)) should be able to be linked with the furniture from [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) and [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143), and medical modules like the Vitals Centre and the Intravenous Drip Stand ([Vanilla Furniture Expanded - Medical Module](https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613)), and the Wall Vitals Monitor ([Wall Vitals Monitor](https://steamcommunity.com/sharedfiles/filedetails/?id=1334289344))
- [ ] Cloth hammock ([[JPT] Soft Warm Beds](https://steamcommunity.com/sharedfiles/filedetails/?id=1713295858)) should be linkable with [More Furniture[1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) and [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) linkables
- [ ] [Rimkea](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959) beds should be linked to [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) linkables
- [ ] [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) beds should be linked to [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) linkables
- [ ] Bedrolls should be linked to [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) and [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) linkables
- [ ] RimThermoPlas Bedrolls ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331)) should be linked to [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) and [More Furniture[1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) linkables
- [ ] Production tables from [Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936) should be made linkable to the Drug Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)) and the RimPlas Drug Cabinet ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331))
- [ ] Rolling table [(Rolling Table)](https://steamcommunity.com/sharedfiles/filedetails/?id=935099161) should be made linkable to the Drug Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)) and the RimPlas Drug Cabinet ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331))
- [ ] Matterweaver and Mechanite Assembly ([Sparkling Worlds - Full Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922)) should be made linkable to the Fabrication and Machining Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
- [ ] Mechanoid Workshop [(What the hack?!)](https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869) should be made linkable to the Fabrication and Machining Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
- [ ] Charcoal Smithy ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851)) should be made linkable to Smithing Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
- [ ] Charcoal Stove ([Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851)) should be made linkable to Kitchen Sink Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
_________________________________________________________________
Stuffable:
- [x] Dark wood planks ([Rimkea](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959)) should be in a drop-down menu with Light wood planks and smooth wood floor ([Rimkea](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959)), or all three should be made stuffable
- [x] ~~Wood Panels ([(O21) Clutter Structures](https://steamcommunity.com/sharedfiles/filedetails/?id=2008681009)) should be made stuffable~~
**Defined as wood panels, will leave as wood**
- [x] ~~Huge Water Tower ([Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)) should be made stuffable~~
**Will consider in the future. I will need to make a new mask texture for this to look good.**
_________________________________________________________________
Misc:

- [x] If you have [Rimatomics ](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465)loaded, the Nuclear Reactor ([Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)) and the Compact Fission Reactor ([Sparkling Worlds - Full Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922)) shouldn't appear, since there's a much more complex system added by [Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465)
- [x] ~~If you have [O21] Shield Generators and [Vanilla Furniture Expanded - Security](https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007) loaded, only the shields from [O21] Shield Generators should appear, since they do exactly the same thing _[Neronix has currently hidden his mod, so I can't link the Shield Generators mod!]_~~
**Mod doesn't exist**
- [x] Lamp End Table ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143)) should require circular glass
- [x] Both Chemlamps ([Vanilla Furniture Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119)) should require glass
- [x] Grow Lamp ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936)) should require circular glass
- [x] Ceiling Light and Graphene Ceiling Light ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331)) should require glass
- [x] Grow Light Fixture ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936)) should require glass (maybe decrease the steel cost from 20 to 15)
- [x] If [Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) and [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) are loaded, remove the File cabinet from [More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) since both mods have the same cabinet serving the same purpose
- [x] If [Medieval - Vanilla [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2011469982) is loaded, remove the Power and Ship architect menus, since the mod removes tech after Medieval levels
- [x] if [Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851) and [Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268) are loaded, put the Clothes washing tub in the Hygiene Tab

**Comment by DrZhivago1** [comment]
I know it's tedious, but if you can turn the mod names into mod name links like with the other post, it helps a lot on my end

**Comment by LeriWeill** [comment]
And done!

**Comment by DrZhivago1** [comment]
Is noble clothing something from Royalty?

**Comment by LeriWeill** [comment]
Noble clothes are indeed from Royalty! I'll make sure to mark Royalty-specific requests if I add some more stuff to the list.

**Comment by DrZhivago1** [comment]
Thanks for keeping track of the updates in the issues. I'll probably do another mass-add and close the other dropdown suggestion issue later. I've also included some new templates for posting bugs or issues in the future, which you may find useful.

**Comment by LeriWeill** [comment]
That's the least I can do to help! I'll make sure to use the new template next time 👍

**Comment by DrZhivago1** [comment]
It's pretty much the same template that you have above, I just have it accessible now. Also made one for Bug Reports

**Comment by DrZhivago1** [comment]
I'm going to ask that you reformat the "Linkables" section in your request here. I need more info about the specific linkables desired.

That being said, I'm going to close this issue and if you can create a new one in the new format that'll work better. You can include new desires as well once I push the next update.
