### ISSUE TITLE
1.1-master : RimKea designation category not getting removed

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#56]
Hey there, it's me with another issue. It seems like in the latest master build, the RimKea category doesn't get removed properly. All the furniture is in the right places but the RimKea category is still there, empty and angry.
You can replicate that by loading **Harmony**, **Core**, **Royalty**, **HugsLib**, **RimKea** and **DocWorld**. Here's the log even though you might already know what needs fixing : https://gist.github.com/dee914ba03100fb9bb3e47cc0df93b67

In other unrelated news, Alpha Biomes updated and added new buildings and floors : _New building: Tar Pits Exotic Smelter, to convert the resin to processed resin
New building: Tar Pump. Can be built on tarred mud (with a penalty) or directly on a tar hole. It produces chemfuel and asphalt.
New floors: asphalt can be used to build tarmac and asphalt bridges, which can be built to increase movement speed on this biome
New security options: asphalt can be used to build tar shells and tar IEDs, which create tar puddles that decrease movement speed to 6%. This tar destroys many floors, and if it rains... it will harden and not go away._
You might wanna update your patch :D

**Comment by DrZhivago1** [comment]
Yea fixed it. RIMkea has a spelling mistake in their Defs that I thought was my mistake. I unfixed my fix to match the spelling error.
