### ISSUE TITLE
Feature Request - Functional Vanilla Expanded Props

### ISSUE THREAD

**Issue by transbiod** [DrZhivago1/DocWorld#57]
### Replace structure and move items to different category
_________________________________________________________________
[Hot meals](https://steamcommunity.com/sharedfiles/filedetails/?id=2110968173&searchtext=hot+meals)
- [x] Move to culinary from production (Microwave)
_________________________________________________________________
[Hot Meals](https://steamcommunity.com/sharedfiles/filedetails/?id=2110968173&searchtext=hot+meals) & [Functional Vanilla Expanded Props
](https://steamcommunity.com/workshop/filedetails/?id=2103216991)
- [ ] If both mods loaded together, replace Microwave from Hot Meals with Microwave (Powered) from Functional Vanilla Expanded Props
- [ ] Move to culinary from storage (Microwave (Powered), Oven (Powered) )
_________________________________________________________________
Thank you!

**Comment by transbiod** [comment]
Actually, i would like to know your opinion on category for microwave, cause i'm a bit torn between temperature and culinary. Alternatively it can go into misc category, but it's already a bit bloated imo.

**Comment by DrZhivago1** [comment]
Just based on the fact that's it's a microwave, I'd say Culinary. I'll check it out.

**Comment by DrZhivago1** [comment]
I looked into the mod _Functional Vanilla Expanded Props_, and I'm not crazy about the implementation of their ideas.

What I propose is to make the "props" into usable items if Deep Storage and/or Hot Meals is loaded. I would not create duplicate (or triple!!) items, but I also think I would not allow pawns to store food inside the microwave or oven. I'd also remove some of the minor spelling mistakes. This would also remove the need to have that mod installed.

What do you think?

**Comment by transbiod** [comment]
Huh, ok, i like this idea MUCH better. But won't it create problems with differencing between normal and usable ones? Since they're kind of mushed together with dropdown menus in their own category.

**Comment by transbiod** [comment]
My EU brain got very dumpy in the morning :/ If by "make the props into usable items" you meant "also move usable items in the appropriate category", then it is indeed THE best way to do it.

**Comment by LeriWeill** [comment]
This is not my issue but I like the idea very much. I thought about suggesting it to you but it seemed a bit much to ask; if you're willing to do it though, so be it :D

**Comment by DrZhivago1** [comment]
Yes, there would be no "static" version of the usable props. Functional props would be moved into appropriate categories. Otherwise the static versions would be left in Decor. This would depend on which mods are loaded.

Right now I can mirror what the other mod changed into usable props. So some **Deep Storage** items, and some **Hot Meals** items.

I haven't looked into the Vanilla Props mod too much, so I'm not sure what I would want to be functional vs what I think is just excessive or repetitive to make functional. It would be a medium sized project, but not out of the scope of this mod.

**Comment by transbiod** [comment]
I think that there isn't a lot of "interesting" props that should be made intractable besides Deep Storage and Hot meals ones. I only thought about water dispenser with ability to dispense water and not much else, considering that other items are either too vague to give some meaningful stats/interactions or too specific, like dinner set or a bin bag, that really should be left as is in my opinion.

**Comment by LeriWeill** [comment]
The ones that could be used as Deep Storage would be the Empty Food Boxes and the Pallet with Green Barrels IMHO

**Comment by DrZhivago1** [comment]
Well if either/both of you want to put together a list of which items you think would be useful to have as functional buildings instead of just props, feel free to leave a comment with a break down of the:
- required mods
-item names
-the function of the item when usable

Then I can see about integration and add my own personality to it.

**Comment by transbiod** [comment]
_________________________________________________________________
[LWM's Deep Storage](https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896)
**Cargo container** - larger version of skip with more capacity
**Pallet with green barrels** - a way to store chemfuel, sewage (Dubs bad hygiene), biosolids (Dubs bad hygiene), nuclear waste (Rimatomics) and oil barrel (Rimefeller)
**Wine rack** is a personal preference. I just like the idea of storing my ingame wine in a fancy way. **Can be safely ignored**.
**Spacer container** - advanced variation of shelf 1x1 with more capacity
**Large spacer container** - same as above, but for double shelf
**Advanced storage device** - more compact version of cargo container for space tech
_________________________________________________________________
[Hot meals](https://steamcommunity.com/sharedfiles/filedetails/?id=2110968173)
**Microwave** - change texture of the same item from Hot meals.
_________________________________________________________________
[Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268)
**Water dispenser** - a way for colonist to drink water other then from sink. Maybe add filtering feature to it to differentiate?
**Washing machine**  - /optional/ change texture of the same item from bad hygiene
_________________________________________________________________
[Vanilla](https://store.steampowered.com/app/294100/RimWorld/)
**Hedge** - i love the idea behind this item, but think that it would be a hundred times better in a decorative plant form with long lifespan.

**Comment by DrZhivago1** [comment]
All ideas were done, and some extras that I wanted. New file for all the changes, as there were a lot.

The only one not included was the Hedge idea, which I welcome you to repost in a new issue, so that I may revisit it in the future.
