### ISSUE TITLE
Bug Report - Wrong Category

### ISSUE THREAD

**Issue by transbiod** [DrZhivago1/DocWorld#60]
**Bug Description**
Preserving barrel from Apothecary should be in husbandry category
(Production -> Husbandry)

[**HugsLib Error Log**]No error log, just something i noticed.

**Comment by DrZhivago1** [comment]
Interesting, I assumed "Deep Storage" would move it to their storage category since it is a storage item. I'll patch it in there if the mod is loaded.

This one is a bit personal preference, but I think since the main goal of the item is to store food, it'll go into storage.

**Comment by transbiod** [comment]
Oh, nevermind, i was assuming that it needed to go into husbandry from the LeriWeill misc Suggestions
