### ISSUE TITLE
Feature Request - Medical Supplements patch

### ISSUE THREAD

**Issue by transbiod** [DrZhivago1/DocWorld#61]
### Move items to different category and add Drop-down menu
_________________________________________________________________
[Medical Supplements](https://steamcommunity.com/sharedfiles/filedetails/?id=1600830185)
- [x] Move to "Beds" from misc (Guest medical mat, Guest medical mat (Ultra tech), Guest medical mat (Spacer Tech), Guest medical mat (Early), Medical mat, Medical mat (Spacer tech), Medical mat (Ultra tech), Medical mat (Early) )
- [x] Move to "Production" from misc (Drug Chemical Mixer)
- [ ] ~~Put all guest mat variations in a drop-down menu with guest medical mat~~
**Guest Beds do not exist**
- [x] Put all medical mat variations in a drop-down menu with medical mat
_________________________________________________________________
Thank you!

**Comment by transbiod** [comment]
On the topic of medical stuff, i noticed, that even with 390+ mods i have only one structure in "Animals" and that is animal medical bed. Is it intended for it to be there, when all the other animal beds are in a "Beds" category?

**Comment by DrZhivago1** [comment]
Animal beds are meant to be detected and moved into the Animal category. Could be something changed and requires attention, or simply that a mod is not patched. If you could grab a hugs lib and define the exact mods that are adding your beds that'd be great.

**Comment by transbiod** [comment]
I think that all of my beds are from vanilla - Animal sleeping spot, Animal sleeping box, Animal bed 
[Hugslib log](https://gist.github.com/696edf8a058d4ec50b8878920a4b2b77)

**Comment by DrZhivago1** [comment]
In that case, do you know which mod the medical bed specifically is from?

**Comment by transbiod** [comment]
Yes, [Animal Medical Bed](https://steamcommunity.com/sharedfiles/filedetails/?i)

**Comment by DrZhivago1** [comment]
Bed issue fixed

**Comment by DrZhivago1** [comment]
I do not see any guest versions of the beds that you mention.

**Comment by transbiod** [comment]
Oh, i think they appear only when Hospitality is loaded with Medical Supplements. Sorry, totally forgot about that.

**Comment by DrZhivago1** [comment]
Tried that, still didn't see them

**Comment by transbiod** [comment]
Animal tab is now full and i, too, don't see any guest medical mats
