### ISSUE TITLE
Bug Report - Patching error

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#63]
When you only load [RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331), the RimPlas animal bed is in the Animals architect menu but alone. The other vanilla animal beds are still in the Beds architect menu, instead of the Animals menu.

Mod list to reproduce the error:
- Harmony, Core, Royalty, [RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331), DocWorld

No log because this doesn"t create any error!

**Comment by DrZhivago1** [comment]
I should probably just change this to be an unconditional thing... ah well. It's fixed now.
