### ISSUE TITLE
Bug Report - Plant Growing Wall Light wall patch outdated

### ISSUE THREAD

**Issue by transbiod** [DrZhivago1/DocWorld#64]
**Bug Description**
[Plant Growing Wall Light](https://steamcommunity.com/sharedfiles/filedetails/?id=1605773857) patch is now outdated. Author merged original mod into [Wall Light](https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208) and renamed item to "Wall Sun Light". Original upload is now considered legacy version for 1.0 users.

Now it needs to be moved from "lighting" to "Husbandry"

**Comment by transbiod** [comment]
Also, i would like to thank you for your awesome work on this project. Two days ago i just wanted to ask for one simple change, and now i report bugs, making suggestions. It just fun in a simple kind of way.

**Comment by DrZhivago1** [comment]
Already done ;)

And thanks, glad that you can contribute and gain satisfaction from it. Maybe you will learn how to xpath in the future!
