### ISSUE TITLE
Bug Report - Storage Architect Icon

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#65]
When you load Architect Icons and DocWorld, the Storage icon is the right one. If you add LWM's Deep Storage to the mix, the Storage icon is an X. 

Mod lists used : 
Core, Royalty, Architect Icons, DocWorld (Icon OK)
Harmony, Core, Royalty, Architect Icons, LWM's Deep Storage, DocWorld (X Icon)

No log since there's no error thrown.

**Comment by DrZhivago1** [comment]
That has nothing to do with DocWorld. You should get the optional addon for icons. Deep Storage is apparently not supported by the main mod.
