### ISSUE TITLE
Misc Suggestions 2: Electric Boogaloo

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#66]
So I'll try to make myself more clear concerning linkables, hope this time it's not as confusing!
In the issue, when I say "Should benefit from", it means that for example the Walls Vitals Monitor should be recognised as a valid improvement for the Glitterworld Hospital Bed, like for the vanilla hospital bed.
_________________________________________________________________
[Sparkling Worlds - Full Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922)

The Glitterworld Hospital Bed:
- [x] Should benefit from the Walls Vitals Monitor ([Wall Vitals Monitor](https://steamcommunity.com/sharedfiles/filedetails/?id=1334289344))
- [x] Should benefit from the Vitals Centre and the Intravenous Drip Stand ([Vanilla Furniture Expanded - Medical Module](https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613))
- [x] Should benefit from the Dresser, the End Table, the Royal end table, the End Table (lamp) and the Royal end table (lamp) ([More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850))
- [x] Should benefit from royal dresser, royal end table, wardrobe and lamp end table ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143))
- [x] Should benefit from the illuminated end table and the illluminated dresser ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079))

 The Matterweaver and Mechanite Assembly:
- [x] Should benefit from the Fabrication and Machining Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
_________________________________________________________________
[[JPT] Soft Warm Beds](https://steamcommunity.com/sharedfiles/filedetails/?id=1713295858)

The Hammock:
- [x] Should benefit from the Dresser, the End Table, the Royal end table, the End Table (lamp) and the Royal end table (lamp) ([More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850))
- [x] Should benefit from royal dresser, royal end table, wardrobe and lamp end table ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143))
- [x] Should benefit from the illuminated end table and the illluminated dresser ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079))
_________________________________________________________________
[Rimkea](https://steamcommunity.com/sharedfiles/filedetails/?id=769201959)

The PILFUR bed, SNOREGG simple bed, SNOREGG double bed, KRUDNEPP simple bed and SNABNEPP double bed:
- [x] Should benefit from royal dresser, royal end table, wardrobe and lamp end table ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143))
- [x] Should benefit from the illuminated end table and the illluminated dresser ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079))
_________________________________________________________________
[Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) 

The simple bed, slab bed, royal poster bed, ergonomic bed and ergonomic double bed:
- [x] Should benefit from the Dresser, the End Table, the Royal end table, the End Table (lamp) and the Royal end table (lamp) ([More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850))
- [x] Should benefit from the lamp end table (Simple bed only) ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143))
- [x] Should benefit from the illuminated end table and the illluminated dresser (Simple bed only) ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079))
_________________________________________________________________
[RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331)

RimThermoPlas bedroll, RimThermoPlas double bedroll, vanilla Bedroll and vanilla double bedroll:
- [x] Should benefit from the Dresser, the End Table, the Royal end table, the End Table (lamp) and the Royal end table (lamp) ([More Furniture [1.1]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850))
- [x] Should benefit from the lamp end table ([Vanilla Furniture Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143))
- [x] Should benefit from the illuminated end table and the illluminated dresser ([Vanilla Furniture Expanded - Spacer Module](https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079))

The High-Tech Hospital Bed:
- [x] Should benefit from the Walls Vitals Monitor ([Wall Vitals Monitor](https://steamcommunity.com/sharedfiles/filedetails/?id=1334289344))

The RimPlas Game-of-Ur, RimPlas Chess Table, RimPlas Stool, RimPlas Shelf, RimPlas Single Shelf, RimPlas Animal Box RimPlas Dining Chair, RimPlas End Table, RimPlas Table (1x1), RimPlas Table (2x1) and RimPlas Dresser:
- [x] Should be removed, since their vanilla counterparts can already be made out of RimPlas

The Graphene Solar Generator, Graphene Wind Turbine:
- [x] Should be made minifiable like their vanilla counterparts
_________________________________________________________________
[Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936)

The Smokeleaf Auto Trimmer, Cultivation bench and medicinals lab:
- [x] Should benefit from the Drug Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)) 
- [x] Should benefit from the RimPlas Drug Cabinet ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331))

The Hempene Solar Generator and the Hempoline-powered Generator:
- [x] Should be made minifiable lie their vanilla counterparts
_________________________________________________________________
[Rolling Table](https://steamcommunity.com/sharedfiles/filedetails/?id=935099161)

The Rolling Table:
- [x] Should benefit from the Drug Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)) 
- [x] Should benefit from the RimPlas Drug Cabinet ([RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331))
_________________________________________________________________
[Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)

The Electric Drug Lab:

- [x] Should benefit from the trimming tools ([Smokeleaf Industry Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=1876387936))
_________________________________________________________________
[What the hack?!](https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869)

The Mechanoid Workshop:
- [x] Should benefit from the Fabrication and Machining Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))
_________________________________________________________________
[Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851)

The Charcoal Generator:
- [x] Should be made minifiable like its vanilla counterpart

The Charcoal Smithy:
- [x] Should benefit from the Smithing Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))

The Charcoal Stove:
- [x] Should benefit from the Kitchen Sink Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632))

The Apothecary Table:
- [x] Should benefit from the Drug Cabinet ([Vanilla Furniture Expanded - Production](https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632)) 
_________________________________________________________________
[Mamuffalo](https://steamcommunity.com/sharedfiles/filedetails/?id=2053120429)

The Mamuffalo:
- [x] Should yield bluefur like the vanilla muffalo and not plainleather
_________________________________________________________________
[Medpod](https://steamcommunity.com/sharedfiles/filedetails/?id=2153065191)

The MedPod and MedPod Lux:
- [x] Should be in the Bed menu
_________________________________________________________________
[Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477)

The Advanced Wind Turbine, advanced solar generator, Helixien gas powered generator, industrial wood-fired generator, industrial chemfuel powered generator and industrial helixien gas powered generator:
- [x] Should be minifiable like their vanilla counterparts
_________________________________________________________________
[Genetic Rim](https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502)

The Cryo-stabilized generator:
- [x] Should be minifiable like its vanilla counterpart
_________________________________________________________________
[Vanilla Factions Expanded - Settlers](https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119)

The Windmill:
- [x] Should be minifiable like its vanilla counterpart
_________________________________________________________________
[Alpha Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677)

The Core sample drill: 
- [x] Should be in a drop-down menu with the vanilla deep drill
_________________________________________________________________
[Dragon's Descent](https://steamcommunity.com/sharedfiles/filedetails/?id=2026992161)

The Dragon Pillow and Dragon Nest: 
- [x] Should be in the Animals category

**Comment by DrZhivago1** [comment]
Looks good to me!

**Comment by DrZhivago1** [comment]
Starting to work through these, let me know if you run into any errors. I haven't been as attentive.

**Comment by LeriWeill** [comment]
Playtested for a few minutes, all the changes seem to be on point (as well as the mead and whiskey in the bottle racks!). The new fur bed from VFE - Vikings could use the same treatment, I'll add it at the end of the list hehe.

**Comment by DrZhivago1** [comment]
Finally done. Thanks for the patience and ideas for making the mod better!
