### ISSUE TITLE
Bug Report: Medieval - Vanilla patch not working 

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#67]
I started creating a modlist for a medieval game, and noticed that the patch affecting the Power and Ship Designation Category removal didn't seem to take effect. Maybe it's because of the 1.2 update of the mod?

I tested it with Core, Royalty, Medieval - Vanilla and DocWorld; the Ship and Power categories were still there.

No log to link since there was no error.

**Comment by DrZhivago1** [comment]
Mod name change

**Comment by DrZhivago1** [comment]
Mod name change
