### ISSUE TITLE
Feature Request: Update patches for Pelador's mods

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#68]
Pelador won't mod anymore for Rimworld, so Mlie took his mods and updated them. If you could update the patches for the mods that would be great!
_________________________________________________________________
[Apothecary](https://steamcommunity.com/sharedfiles/filedetails/?id=2000244851)
- [x] Update the mod's patches for [Apothecary (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2195469123)
_________________________________________________________________
[Rimoleum](https://steamcommunity.com/sharedfiles/filedetails/?id=2004334162) 
- [x] Update the mod's patches for [Rimoleum (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2194437011)
_________________________________________________________________
[RimPlas](https://steamcommunity.com/sharedfiles/filedetails/?id=2004190331) 
- [x] Update the mod's patches for [RimPlas (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2194993727)
_________________________________________________________________
(Bonus 1) [Preemptive Strike](https://steamcommunity.com/sharedfiles/filedetails/?id=1890377807) 
- [x] Update the mod's patches for [Preemptive Strike (Fork)](https://steamcommunity.com/sharedfiles/filedetails/?id=2056230561)
_________________________________________________________________
(Bonus 2) [More Furniture [1.1 + 1.2]](https://steamcommunity.com/sharedfiles/filedetails/?id=2018490850) 
- [x] The mod hasn't changed but its name has, I believe it's screwing your patches up

**Comment by DrZhivago1** [comment]
Wish these motherfuckers would stop changing their mod names and stick without having the [1.1] or [1.2] shite. ANYHOW... fixed them.
