### ISSUE TITLE
Feature Request - Research consolidation

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#70]
I hope you don't mind spamming you with requests, especially since you seem to have more important stuff to look after than GitHub and DocWorld at the moment.
I don't know how annoying or not it is to mess with techs and researches, but some mods create projects that basically are the same; so here are some suggestions to "de-clutter" the tree.
_________________________________________________________________
[Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness)
- [x] Long Blades (Vanilla) requires Basic Tool Crafting ([Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness)), as well as smithing.
_________________________________________________________________
When [Vanilla Factions Expanded - Medieval](https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450&searchtext=factions+medieval) & [Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness) are both loaded
- [x] Basic Crossbows ([Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness)) requires the Greatbow (Vanilla) research, as well as Basic Tool Crafting ([Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness))
- [x] Merge Heavy Crossbows ([Medieval Madness: Tools of the Trade](https://steamcommunity.com/sharedfiles/filedetails/?id=1851407975&searchtext=medieval+madness)) and Heavy Crossbows ([Vanilla Factions Expanded - Medieval](https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450&searchtext=factions+medieval)) for a cost of 1100 points.
_________________________________________________________________
When [Vanilla Armour Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282&searchtext=armour) & [[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included) are both loaded
- [x] Merge Simple Apparel ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included)) and Leather Tanning ([Vanilla Armour Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282&searchtext=armour)), keep the Leather Tanning name 
- [x] Merge Light Armour ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included)) and Plate Armor (Vanilla), and make Plate Armor a pre-requisite for Heavy Armour ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included))
_________________________________________________________________
When [[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included) & [Vanilla Factions Expanded - Medieval](https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450&searchtext=factions+medieval) are both loaded
- [x] Move Heavy Plate Armor and Heavy Plate Helmet ([Vanilla Factions Expanded - Medieval](https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450&searchtext=factions+medieval)) from Plate Armor research to Heavy Armour ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included)) research
_________________________________________________________________
When [Vanilla Factions Expanded - Vikings](https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285) & [[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included) are both loaded
- [x] Move Guardian Armor and Guardian Helmet ([Vanilla Factions Expanded - Vikings](https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285)) from Plate Armor (Vanilla) to Heavy Armour ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included))
_________________________________________________________________
When [Vanilla Weapons Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360&searchtext=weapons+expanded) & [[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included) are both loaded
- [x] Merge Gunpowder research ([Vanilla Weapons Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360&searchtext=weapons+expanded)) and Flintlock Guns ([[O21] Dragons Not Included](https://steamcommunity.com/sharedfiles/filedetails/?id=2008882134&searchtext=dragons+not+included))
_________________________________________________________________
When [Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465) & [Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477) are both loaded
- [x] Remove the Nuclear Power Research from [Vanilla Furniture Expanded - Power](https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477), since the Nuclear Reactor is already removed
_________________________________________________________________
When [Rimatomics](https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465) & [Sparkling Worlds - Full Mod
](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922) are both loaded
- [x] Remove the Nuclear Power Research from [Sparkling Worlds - Full Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922), since the Nuclear Reactor is already removed
_________________________________________________________________

I hope I didn't make any mistake or mix-up in my suggestions!

**Comment by DrZhivago1** [comment]
It's not a problem, I'll make some time to get around to the requests that I've been sitting on.

**Comment by DrZhivago1** [comment]
Done
