### ISSUE TITLE
Feature Request :  Small compat, again

### ISSUE THREAD

**Issue by LeriWeill** [DrZhivago1/DocWorld#71]
Another small compat that could be nice:

_________________________________________________________________
[LWM's Deep Storage](https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896), [Vanilla Brewing Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858) and [Vanilla Furniture Expanded - Props & Decor](https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149)

If the three mods are loaded:
- [x] Allow Double-aged whiskey ([Vanilla Brewing Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858)) to be stored in the bottle rack ([Vanilla Furniture Expanded - Props & Decor](https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149)) 
_________________________________________________________________
[LWM's Deep Storage](https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896), [Vanilla Factions Expanded - Vikings](https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285) and [Vanilla Furniture Expanded - Props & Decor](https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149)

If the three mods are loaded:
- [x] Allow Mead ([Vanilla Factions Expanded - Vikings](https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285)) to be stored in the bottle rack ([Vanilla Furniture Expanded - Props & Decor](https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149))

**Comment by DrZhivago1** [comment]
Done
