### ISSUE TITLE
Bug Report - Able to build the Electric Stove without Electricity...

### ISSUE THREAD

**Issue by Ecu** [DrZhivago1/DocWorld#85]
This seems to be related to how DocWorld creates stuffed menus.  The default for stoves is the electric, even if electricity hasn't been researched.  This allows you to quick select it and place it down for building, even if you've not actually researched the tech.  Opening the submenu shows that you should only be able to build a fueled stove correctly, it is just the default selected that ends up allowing you to bypass this.

**Comment by DrZhivago1** [comment]
Vanilla dropdown bug, can't fix it on my end. It will go away when you select the proper stove. Just choose not to abuse it.
