### ISSUE TITLE
Bug Report - ToolCabinet draws 4,4

### ISSUE THREAD

**Issue by Kayedon** [DrZhivago1/DocWorld#86]
**Bug Description**
When used with Gloomy Vanilla Overhaul, the regular ol' Tool Cabinet draws its texture 4x4 rather than 2x1. Building size remains the same.

Noted in the comments here: https://steamcommunity.com/sharedfiles/filedetails/?id=1883678698

**Comment by DrZhivago1** [comment]
Yup, it's on the fault of GVO for changing Vanilla texture draw size. I don't plan on redrawing it, and GVO isn't really supported by author atm so yea...

If you don't want it, don't use the texture portion of DocWorld
